CREATE TABLE CLIENTE_CLI (
    CLI_CDCLIENTE INT NOT NULL AUTO_INCREMENT,
    CLI_NMCLIENTE VARCHAR(255) NOT NULL,
    CLI_DSCIDADE VARCHAR(255) NOT NULL,
    CLI_DSUF CHAR(2) NOT NULL,
    CLI_DTCADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CLI_USCADASTRO VARCHAR(255) NOT NULL,
    CLI_DTALTERACAO TIMESTAMP,
    CLI_USALTERACAO VARCHAR(255),
    CONSTRAINT UCK_CDCLIENTE UNIQUE (CLI_CDCLIENTE),
    CONSTRAINT PRK_CDCLIENTE PRIMARY KEY (CLI_CDCLIENTE)
);

-- Criando indices
CREATE INDEX IDX_NMCLIENTE ON CLIENTE_CLI (CLI_NMCLIENTE);
CREATE INDEX IDX_DSCIDADE ON CLIENTE_CLI (CLI_DSCIDADE);
CREATE INDEX IDX_DSUF ON CLIENTE_CLI (CLI_DSUF);

DELIMITER //

CREATE TRIGGER INS_CLIENTE_CLI
BEFORE INSERT ON CLIENTE_CLI
FOR EACH ROW
BEGIN
    -- Preenche CLI_DTCADASTRO com a data e hora atual
    SET NEW.CLI_DTCADASTRO = NOW();
    
    -- Preenche CLI_USCADASTRO com o usuário da variável de sessão
    SET NEW.CLI_USCADASTRO = @USERNAME;
END //

DELIMITER ;

DELIMITER //

CREATE TRIGGER UPD_CLIENTE_CLI
BEFORE UPDATE ON CLIENTE_CLI
FOR EACH ROW
BEGIN
    -- Preenche CLI_DTALTERACAO com a data e hora atual
    SET NEW.CLI_DTALTERACAO = NOW();
    
    -- Preenche CLI_USALTERACAO com o usuário da variável de sessão
    SET NEW.CLI_USALTERACAO = @USERNAME;
END //

DELIMITER ;

insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('JOSUÉ CONÇALVES', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('MARIA DA PIEDADE', 'UBERLANDIA', 'MG');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('JUVENAL JUVENCIO', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('VALENTINA CORAJOSA', 'RIO DE JANEIRO', 'RJ');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('JOÃO MARIA', 'BLUMENAU', 'SC');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('MARIA JOÃO', 'BLUMENAU', 'SC');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('EVERALDO EVARISTO', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('RONIELSO RUSTICO', 'BELÉM', 'PR');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('YURI ALBERTO', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('FAGNER AÇOUGUEIRO', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('XAROPINHO DORFLEX', 'CURITIBA', 'PA');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('RENATO ARAGÃO', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('RAPHAEL VEIGA', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('ANITA CALDERON', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('EVITTA PERON', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('ALEXANDRE COLUNAS', 'GOIÂNIA', 'GO');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('RONALDO CAIADO', 'GOIANIA', 'GO');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('MAIKE HOT-DOG', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('CONSTANCE NUÑES', 'SÃO PAULO', 'SP');
insert into CLIENTE_CLI (CLI_NMCLIENTE, CLI_DSCIDADE, CLI_DSUF) values ('ROSANGELA FLORES', 'SÃO PAULO', 'SP');