CREATE TABLE ITEMPEDIDO_ITE (
    ITE_SEQ INT NOT NULL AUTO_INCREMENT,
    PED_NRPEDIDO INT NOT NULL,
    PRO_CDPRODUTO INT NOT NULL,
    ITE_QTDE NUMERIC(15, 4) NOT NULL DEFAULT 0.0000,
    ITE_VLUNITARIO NUMERIC(15, 4) NOT NULL,
    ITE_VLTOTAL NUMERIC(15, 4) GENERATED ALWAYS AS (ITE_QTDE * ITE_VLUNITARIO) STORED,
    ITE_DTCADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ITE_USCADASTRO VARCHAR(255) NOT NULL,
    ITE_DTALTERACAO TIMESTAMP,
    ITE_USALTERACAO VARCHAR(255),
    CONSTRAINT UCK_ITE_SEQ UNIQUE (ITE_SEQ),
    CONSTRAINT PRK_ITE_SEQ PRIMARY KEY (ITE_SEQ),
    CONSTRAINT FRK_ITEMPEDIDO_PEDIDO FOREIGN KEY (PED_NRPEDIDO) REFERENCES PEDIDO_PED(PED_NRPEDIDO),
    CONSTRAINT FRK_ITEMPEDIDO_PRODUTO FOREIGN KEY (PRO_CDPRODUTO) REFERENCES PRODUTO_PRO(PRO_CDPRODUTO)    
);

-- Índice para otimizar consultas pelo número do pedido
CREATE INDEX IDX_ITEMPEDIDO_PED_NRPEDIDO ON ITEMPEDIDO_ITE (PED_NRPEDIDO);
-- Índice para otimizar consultas pelo código do produto
CREATE INDEX IDX_ITEMPEDIDO_PRO_CDPRODUTO ON ITEMPEDIDO_ITE (PRO_CDPRODUTO);

DELIMITER //

CREATE TRIGGER INS_ITEMPEDIDO_ITE
BEFORE INSERT ON ITEMPEDIDO_ITE
FOR EACH ROW
BEGIN
    SET NEW.ITE_DTCADASTRO = NOW();
    SET NEW.ITE_USCADASTRO = @USERNAME;
END //

DELIMITER ;

DELIMITER //

CREATE TRIGGER UPD_ITEMPEDIDO_ITE
BEFORE UPDATE ON ITEMPEDIDO_ITE
FOR EACH ROW
BEGIN
    SET NEW.ITE_DTALTERACAO = NOW();
    SET NEW.ITE_USALTERACAO = @USERNAME;
END //

DELIMITER ;
