CREATE TABLE PEDIDO_PED (
    PED_NRPEDIDO INT NOT NULL AUTO_INCREMENT,
    PED_DTEMISSAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CLI_CDCLIENTE INT NOT NULL,
    PED_VLTOTAL NUMERIC(15, 4) NOT NULL DEFAULT 0.0000,
    PED_DTCADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PED_USCADASTRO VARCHAR(255) NOT NULL,
    PED_DTALTERACAO TIMESTAMP,
    PED_USALTERACAO VARCHAR(255),
    CONSTRAINT UCK_NRPEDIDO UNIQUE (PED_NRPEDIDO),
    CONSTRAINT PRK_NRPEDIDO PRIMARY KEY (PED_NRPEDIDO),
    CONSTRAINT FRK_PEDIDO_CLIENTE FOREIGN KEY (CLI_CDCLIENTE) REFERENCES CLIENTE_CLI(CLI_CDCLIENTE)
);

-- Índice para otimizar consultas pelo código do cliente
CREATE INDEX IDX_PEDIDO_CLI_CDCLIENTE ON PEDIDO_PED (CLI_CDCLIENTE);
-- Índice para otimizar consultas pela data de emissão do pedido
CREATE INDEX IDX_PEDIDO_DTEMISSAO ON PEDIDO_PED (PED_DTEMISSAO);

DELIMITER //

CREATE TRIGGER INS_PEDIDO_PED
BEFORE INSERT ON PEDIDO_PED
FOR EACH ROW
BEGIN
    SET NEW.PED_DTCADASTRO = NOW();
    SET NEW.PED_USCADASTRO = @USERNAME;
END //

DELIMITER ;

DELIMITER //

CREATE TRIGGER UPD_PEDIDO_PED
BEFORE UPDATE ON PEDIDO_PED
FOR EACH ROW
BEGIN
    SET NEW.PED_DTALTERACAO = NOW();
    SET NEW.PED_USALTERACAO = @USERNAME;
END //

DELIMITER ;