CREATE TABLE PRODUTO_PRO (
    PRO_CDPRODUTO INT NOT NULL AUTO_INCREMENT,
    PRO_NMPRODUTO VARCHAR(255) NOT NULL,
    PRO_VLUNITARIO NUMERIC(15,4) NOT null,
    PRO_DTCADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRO_USCADASTRO VARCHAR(255) NOT NULL,
    PRO_DTALTERACAO TIMESTAMP,
    PRO_USALTERACAO VARCHAR(255),
    CONSTRAINT UCK_CDPRODUTO UNIQUE (PRO_CDPRODUTO),
    CONSTRAINT PRK_CDPRODUTO PRIMARY KEY (PRO_CDPRODUTO)
);

-- Criando indices
CREATE INDEX IDX_NMPRODUTO ON PRODUTO_PRO (PRO_NMPRODUTO);

DELIMITER //

CREATE TRIGGER INS_PRODUTO_PRO
BEFORE INSERT ON PRODUTO_PRO
FOR EACH ROW
BEGIN
    -- Preenche PRO_DTCADASTRO com a data e hora atual
    SET NEW.PRO_DTCADASTRO = NOW();
    
    -- Preenche PRO_USCADASTRO com o usuário da variável de sessão
    SET NEW.PRO_USCADASTRO = @USERNAME;
END //

DELIMITER ;

DELIMITER //

CREATE TRIGGER UPD_PRODUTO_PRO
BEFORE UPDATE ON PRODUTO_PRO
FOR EACH ROW
BEGIN
    -- Preenche PRO_DTALTERACAO com a data e hora atual
    SET NEW.PRO_DTALTERACAO = NOW();
    
    -- Preenche PRO_USALTERACAO com o usuário da variável de sessão
    SET NEW.PRO_USALTERACAO = @USERNAME;
END //

DELIMITER ;

insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('PILHA RECARREGÁVEL', 50.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('FONES BLUETOTH NÃO ORIGINAIS', 19.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('MOUSE SEM FIO', 25.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('FITA DUPLA FACE', 5.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('LIVRETO DE ANOTAÇÕES', 9.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('REFIL FICHARIO', 19.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('PENDRIVE 36GB', 20.50);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CARTÃO DE MEMORIA 64GB', 75.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('ANEL DE BORRACHA', 5.50);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('ADAPTADOR USB-C', 19.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CORDÃO PARA CRACHÁ', 5.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('DVD-RW DUPLA GRAVAÇÃO', 5.90);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CANETA ESFEROGRÁFICA PRETA', 1.50);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CANETA ESFEROGRÁFICA AZUL', 1.50);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CANETA ESFEROGRÁFICA VERMELHA', 1.50);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CANETA ESFEROGRÁFICA VERDE', 1.50);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CANETA ESFEROGRÁFICA ROSA', 1.50);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CANETA ESFEROGRÁFICA ROXA', 1.50);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CANETA ESFEROGRÁFICA LARANJA', 1.50);
insert into PRODUTO_PRO (PRO_NMPRODUTO, PRO_VLUNITARIO) values ('CANETA MARCA TEXTO', 3.50);