CREATE TABLE SEQUENCE_TABLE (
    SEQ_NAME VARCHAR(50) NOT NULL,
    SEQ_VALUE INT NOT NULL,
    CONSTRAINT UCK_SEQ_NAME UNIQUE (SEQ_NAME),
    CONSTRAINT PRK_SEQ_NAME PRIMARY KEY (SEQ_NAME)
);

-- Insere uma sequência inicial
INSERT INTO SEQUENCE_TABLE (SEQ_NAME, SEQ_VALUE) VALUES ('CLIENTE_CLI_SEQ', 1);
INSERT INTO SEQUENCE_TABLE (SEQ_NAME, SEQ_VALUE) VALUES ('PRODUTO_PRO_SEQ', 1);
INSERT INTO SEQUENCE_TABLE (SEQ_NAME, SEQ_VALUE) VALUES ('PEDIDO_PED_SEQ', 1);

DELIMITER //

create PROCEDURE GetNextSequenceValue (IN pSEQ_NAME VARCHAR(30), OUT next_val INT)
BEGIN
    -- Atualiza e obtém o próximo valor da sequência
    UPDATE SEQUENCE_TABLE SET SEQ_VALUE = SEQ_VALUE + 1 WHERE SEQ_NAME = pSEQ_NAME;
    SELECT SEQ_VALUE INTO next_val FROM SEQUENCE_TABLE WHERE SEQ_NAME = pSEQ_NAME;
END //

DELIMITER ;
